chore: Update GitHub Actions workflows for better readability and maintainability

diff --git a/.github/workflows/automated_tests.yaml b/.github/workflows/automated_tests.yaml
--- a/.github/workflows/automated_tests.yaml
+++ b/.github/workflows/automated_tests.yaml
@@ -1,5 +1,7 @@
 name: Automated Tests
-on: [push, workflow_dispatch]
+on:
+  push:
+  workflow_dispatch:
 
 jobs:
   build_environment:
@@ -12,13 +14,12 @@ jobs:
     runs-on: ubuntu-latest
     container:
       image: ${{ needs.build_environment.outputs.image_name }}
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Build AlkOS
-        run: "$GITHUB_WORKSPACE/scripts/actions/build_alkos.bash" -v
+        run: "$GITHUB_WORKSPACE/scripts/actions/build_alkos.bash -v"
 
       - name: Run tests
         run: python "$GITHUB_WORKSPACE/scripts/tests/runner.py"
@@ -29,7 +30,8 @@ jobs:
 
       - name: Print tests log on failure
         if: failure()
-        run: cat scripts/tests/test_framework_logs/*/failed_tests.log || echo "Test framework log not found"
+        run: |
+          cat scripts/tests/test_framework_logs/*/failed_tests.log || echo "Test framework log not found"
 
       - name: Upload build artifact
         if: always()
